### ISSUE TITLE
Some prep skill questions were never mentioned

### ISSUE THREAD

**Issue by retep-mathwizard** [skilstak/prep#7]
I'm trying to finish up, but I'm stuck on these and they were not mentioned in the `textbook` to my knowledge, I may have missed something:
______ is good socialization practice.
YouTube and blogging are taught in ______.
In which course could I learn Swift programming? ______
______ lead to Data and Languages focus categories.

**Comment by tslnc04** [comment]
1. The first one was changed yesterday.
2. The second was vague, but existed. I do think it should be changed a bit to clarify, though.

> Play, Prep, Yoga, and NewMedia are all at the Preparation level. Stuff here is designed to prepare and maintain your programming and other technical skills as you build them. Before you ask, yes Yoga and YouTube are technical skills. While Yoga and NewMedia are listed without connection to anything they can be taken more than once, but are billed at the Preparation tier. Prep and Play can also be taken more than once but Prep is generally only needed for one semester (or less).

3. It does exist, look under `Main Focus Categories` and `Custom Projects`.
4. Very clear under `Main Focus Categories`.
